package com.spykertech.archeryhandicalc;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import android.os.Bundle;
import android.app.Activity;
import android.view.KeyEvent;
import android.view.Menu;
import android.view.View;
import android.view.View.OnKeyListener;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;

public class MainActivity extends Activity implements OnKeyListener {
	private Spinner roundSpinner;
	private EditText input;
	private TextView output;
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		roundSpinner = (Spinner) findViewById(R.id.spinner1);
		input = (EditText) findViewById(R.id.editText1);
		output = (TextView) findViewById(R.id.textView5);
		input.setOnKeyListener(this);
		buildRoundList();
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}

	public void buildRoundList() {
		List<Round> list = new ArrayList<Round>();
		Round round = new Round("Portsmouth");
		Distance dist = new Distance(20, TargetFace.FITA60, ScoringStyle.TEN_ZONE, false, 60);
		round.addDistance(dist);
		list.add(round);
		round = new Round("FITA 18");
		dist = new Distance(18, TargetFace.FITA40, ScoringStyle.TEN_ZONE, true, 60);
		round.addDistance(dist);
		list.add(round);
		round = new Round("FITA 25");
		dist = new Distance(25, TargetFace.FITA60, ScoringStyle.TEN_ZONE, true, 60);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Combined FITA");
		dist = new Distance(18, TargetFace.FITA40, ScoringStyle.TEN_ZONE, true, 60);
		round.addDistance(dist);
		dist = new Distance(25, TargetFace.FITA60, ScoringStyle.TEN_ZONE, true, 60);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Stafford");
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 60);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Vegas");
		dist = new Distance(18, TargetFace.FITA40, ScoringStyle.FIVE_ZONE, true, 60);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Portsmouth Compound");
		dist = new Distance(20, TargetFace.FITA60, ScoringStyle.TEN_ZONE_COMPOUND, false, 60);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Frostbite");
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Portsmouth 10-6");
		dist = new Distance(20, TargetFace.FITA60, ScoringStyle.FIVE_ZONE, false, 60);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Portsmouth 10-6 Compound");
		dist = new Distance(20, TargetFace.FITA60, ScoringStyle.FIVE_ZONE_COMPOUND, false, 60);
		round.addDistance(dist);
		list.add(round);
		round = new Round("FITA (Gents)");
		dist = new Distance(90, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(70, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("FITA (Ladies)");
		dist = new Distance(70, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Metric II");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Metric III");
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Metric IV");
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(10, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Metric V");
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(15, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(10, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("FITA 900");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 30);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 30);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 30);
		round.addDistance(dist);
		list.add(round);
		round = new Round("FITA 70");
		dist = new Distance(70, TargetFace.FITA122, ScoringStyle.IMPERIAL, true, 72);
		round.addDistance(dist);
		list.add(round);
		round = new Round("FITA 60");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, true, 72);
		round.addDistance(dist);
		list.add(round);
		round = new Round("FITA 50 10-6");
		dist = new Distance(50, TargetFace.FITA80, ScoringStyle.FIVE_ZONE, true, 72);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Half FITA (Gents)");
		dist = new Distance(90, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(70, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Half FITA (Ladies)");
		dist = new Distance(70, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Half Metric II");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Half Metric III");
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Half Metric IV");
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(10, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Half Metric V");
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(15, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		dist = new Distance(10, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 18);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Long Metric (Gents)");
		dist = new Distance(90, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(70, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Long Metric (Ladies)");
		dist = new Distance(70, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Long Metric II");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Long Metric III");
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Long Metric IV");
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Long Metric V");
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Metric I");
		dist = new Distance(50, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Metric II");
		dist = new Distance(40, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Metric III");
		dist = new Distance(30, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Metric IV");
		dist = new Distance(20, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(10, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Metric V");
		dist = new Distance(15, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(10, TargetFace.FITA80, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("FITA Standard");
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.TEN_ZONE, true, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("York");
		dist = new Distance(100, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 72);
		round.addDistance(dist);
		dist = new Distance(80, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Hereford / Bristol I");
		dist = new Distance(80, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 72);
		round.addDistance(dist);
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Bristol II");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 72);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Bristol III");
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 72);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Bristol IV");
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 72);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Bristol V");
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 72);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(10, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Saint George");
		dist = new Distance(100, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(80, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Albion");
		dist = new Distance(80, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Windsor");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Windsor");
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Junior Windsor");
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Junior Windsor");
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		dist = new Distance(10, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("New Western");
		dist = new Distance(100, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(80, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Long Western");
		dist = new Distance(80, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Western");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Western");
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Junior Western");
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Junior Western");
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		list.add(round);
		round = new Round("American");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 30);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 30);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 30);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Saint Nicholas");
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 36);
		round.addDistance(dist);
		list.add(round);
		round = new Round("New National");
		dist = new Distance(100, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(80, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Long National");
		dist = new Distance(80, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("National");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short National");
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		round = new Round("Junior National");
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		round = new Round("Short Junior National");
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 48);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("New Warwick");
		dist = new Distance(100, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		dist = new Distance(80, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Long Warwick");
		dist = new Distance(80, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Warwick");
		dist = new Distance(60, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Warwick");
		dist = new Distance(50, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Junior Warwick");
		dist = new Distance(40, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Short Junior Warwick");
		dist = new Distance(30, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		dist = new Distance(20, TargetFace.FITA122, ScoringStyle.IMPERIAL, false, 24);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Bray I");
		dist = new Distance(20, TargetFace.FITA40, ScoringStyle.TEN_ZONE, false, 30);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Bray II");
		dist = new Distance(25, TargetFace.FITA60, ScoringStyle.TEN_ZONE, false, 30);
		round.addDistance(dist);
		list.add(round);
		round = new Round("Worcester");
		dist = new Distance(20, TargetFace.WORCESTER, ScoringStyle.WORCESTER, false, 60);
		round.addDistance(dist);
		list.add(round);
		Collections.sort(list);
		ArrayAdapter<Round> dataAdapter = new ArrayAdapter<Round>(this, android.R.layout.simple_spinner_item, list);
		dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
		roundSpinner.setAdapter(dataAdapter);
	}

	@Override
	public boolean onKey(View view, int keyCode, KeyEvent event) {
		roundSpinner = (Spinner) findViewById(R.id.spinner1);
		Round round = (Round) roundSpinner.getSelectedItem();
		try {
			output.setText(String.format("%d", round.lookupHandicap(Integer.parseInt(input.getText().toString()))));
		} catch (Exception e) {
			
		}
		return false;
	}
}
